import Head from "next/head";
import { Form, Button } from "react-bootstrap";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function Home() {
  const [walletAddress, setWalletAddress] = useState("");
  const router = useRouter();
  const handleSubmit = (e) => {
    e.preventDefault();
    if (walletAddress !== "") {
      //render the nft collection page
      router.push(`/wallet/${walletAddress}`);
    } else {
      alert("Please enter a wallet address");
    }
  };
  return (
    <>
      <Head>
        <title>NFt Collections</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className="container-fluid"
          style={{
            height: "100vh",
            position: "relative",
            background: "#0bf762",
          }}
        >
          <div className="row mx-auto text-center">
            <div className="col-sm-3"></div>
            <div className="col-sm-6">
              <Form
                onSubmit={handleSubmit}
                className=""
                style={{
                  marginTop: "15em",
                  borderImage:
                    "linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(139,23,210,1) 49%, rgba(0,212,255,1) 86%) 30",
                  borderWidth: "4px",
                  borderStyle: "solid",
                }}
              >
                <label htmlFor="Wallet Address" className="text-light mt-2">
                  Wallet Address:
                </label>
                <br />
                <input
                  value={walletAddress}
                  onChange={(e) => setWalletAddress(e.target.value)}
                  type="text"
                  className="form-control  mb-2 w-50 d-block mx-auto"
                  placeholder="Please enter NFT wallet address......"
                />

                <Button
                  type="submit"
                  className="mb-2 btn-secondary rounded-pill"
                >
                  Search Nfts
                </Button>
              </Form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
